name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - name: Build C++ example
        run: |
          docker run --rm -v $PWD/cpp:/src emscripten/emsdk bash -c "cd /src && ./build.sh"
          mkdir -p public/cpp
          cp cpp/build/ar_viewer.html public/cpp/index.html
          cp cpp/build/ar_viewer.js public/cpp/
          cp cpp/build/ar_viewer.wasm public/cpp/
      - name: Copy static files
        run: |
          mkdir -p public/models
          cp index.html public/index.html
          cp -r models/* public/models/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v2
